import React from 'react';

/**
 * Clean, minimalist report view for PDF exports via window.print()
 */
export const ReportView = ({ title, data, headers, type = 'REPORT' }) => {
  if (!data || !data.length) return null;

  return (
    <div className="print-only p-8 text-black bg-white min-h-screen">
      <div className="flex justify-between items-end mb-8 border-b-2 border-black pb-4">
        <div>
          <h1 className="text-4xl font-black uppercase tracking-tighter">FUEGO POS</h1>
          <p className="text-sm font-bold opacity-60 uppercase">{type} / {new Date().toLocaleDateString()}</p>
        </div>
        <div className="text-right">
          <h2 className="text-xl font-bold uppercase">{title}</h2>
          <p className="text-[10px] opacity-40 uppercase">CONFIDENTIAL INTERNAL REPORT</p>
        </div>
      </div>

      <table className="w-full text-left border-collapse">
        <thead>
          <tr className="border-b border-black">
            {headers.map((h, i) => (
              <th key={i} className="py-2 px-1 text-[10px] font-black uppercase tracking-widest">{h.label}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {data.map((row, i) => (
            <tr key={i} className="border-b border-stone-100">
              {headers.map((h, j) => (
                <td key={j} className="py-2 px-1 text-[11px] font-medium">
                  {h.format ? h.format(row[h.key], row) : row[h.key]}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>

      <div className="mt-12 pt-4 border-t border-dashed border-stone-300 text-[8px] opacity-30 flex justify-between uppercase">
        <span>Generated by Fuego POS System</span>
        <span>Page 1 of 1</span>
        <span>{new Date().toISOString()}</span>
      </div>
    </div>
  );
};
