import { escapeHtml } from './pos';

export const openReportPrintWindow = (title, data, headers) => {
  const printWindow = window.open('', '_blank', 'noopener,noreferrer,width=1120,height=820');

  if (!printWindow) {
    window.alert('Allow pop-ups to export PDF reports.');
    return false;
  }

  const generatedAt = new Date();
  const headerMarkup = headers
    .map((header) => `<th>${escapeHtml(header.label)}</th>`)
    .join('');
  const bodyMarkup = data
    .map((row) => {
      const cells = headers
        .map((header) => {
          const formattedValue = header.format ? header.format(row[header.key], row) : row[header.key];
          return `<td>${escapeHtml(formattedValue)}</td>`;
        })
        .join('');

      return `<tr>${cells}</tr>`;
    })
    .join('');

  printWindow.document.write(`<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>${escapeHtml(title)}</title>
    <style>
      @page {
        size: A4;
        margin: 14mm;
      }
      body {
        margin: 0;
        font-family: Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        color: #111827;
        background: #ffffff;
      }
      .sheet {
        padding: 4mm 0;
      }
      .header {
        display: flex;
        justify-content: space-between;
        align-items: flex-end;
        border-bottom: 2px solid #111827;
        padding-bottom: 12px;
        margin-bottom: 20px;
      }
      .eyebrow {
        font-size: 11px;
        font-weight: 800;
        letter-spacing: 0.28em;
        text-transform: uppercase;
        color: #ea580c;
        margin: 0 0 6px;
      }
      .title {
        font-size: 30px;
        font-weight: 800;
        margin: 0;
      }
      .meta {
        text-align: right;
        font-size: 12px;
        color: #6b7280;
      }
      table {
        width: 100%;
        border-collapse: collapse;
      }
      th {
        text-align: left;
        font-size: 10px;
        letter-spacing: 0.22em;
        text-transform: uppercase;
        color: #6b7280;
        padding: 10px 8px;
        border-bottom: 1px solid #d1d5db;
      }
      td {
        padding: 10px 8px;
        border-bottom: 1px solid #e5e7eb;
        font-size: 12px;
        vertical-align: top;
      }
      .footer {
        display: flex;
        justify-content: space-between;
        margin-top: 18px;
        padding-top: 12px;
        border-top: 1px dashed #d1d5db;
        font-size: 10px;
        color: #6b7280;
        text-transform: uppercase;
      }
    </style>
  </head>
  <body>
    <div class="sheet">
      <div class="header">
        <div>
          <p class="eyebrow">Fuego POS Report</p>
          <h1 class="title">${escapeHtml(title)}</h1>
        </div>
        <div class="meta">
          <div>${escapeHtml(generatedAt.toLocaleDateString())}</div>
          <div>${escapeHtml(generatedAt.toLocaleTimeString())}</div>
        </div>
      </div>
      <table>
        <thead>
          <tr>${headerMarkup}</tr>
        </thead>
        <tbody>
          ${bodyMarkup}
        </tbody>
      </table>
      <div class="footer">
        <span>Generated by Fuego POS</span>
        <span>${escapeHtml(generatedAt.toISOString())}</span>
      </div>
    </div>
  </body>
</html>`);
  printWindow.document.close();
  printWindow.focus();

  window.setTimeout(() => {
    printWindow.print();
    printWindow.onafterprint = () => {
      printWindow.close();
    };
  }, 250);

  return true;
};
